### PR TITLE
upgrade cdk-2.8 to 2.9

### PR DESCRIPTION
**Pull request by RvdPloeg**
Dear Rami,

I have upgraded the cdk library from 2.8 to 2.9. The build went successful. Could you check for regressions? And maybe if you agree to accept a pull request?

Kind regards,

René
cdk programmer

### CODE REVIEW

**Review by RamiManaf — CHANGES_REQUESTED** [review]
Please remove the folder .vscode with settings.json as this is a local settings file.

**Comment by RvdPloeg** [comment]
my mistake. I think it is gone no but double check me. thanks.

**Comment by RamiManaf** [comment]
Thanks for your contribution @RvdPloeg

**Comment by RvdPloeg** [comment]
Dear Rami,

There is a new update of the cdk library. I have adjusted the code as before to work with this new version. The build went successfully. If you accept the changes it may still be essential to check if the program works properly.

Kind regards,

René

**Pull request merged**
